### PR TITLE
Add missing dot command in `lint:fix` script

### PR DESCRIPTION
**Pull request by ianrohde**
🍻

### CODE REVIEW

**Comment by eglove** [comment]
Are you really sure you want all? That's going to take a long time to run on a project of any size. You probably want this:

`eslint --cache --fix`

I'd recommend putting that in a pre-commit hook and using eslint on save locally. Because the on save should only work with your current file. --cache will work with anything you've changed.

**Comment by ianrohde** [comment]
These are manually run scripts. From https://github.com/wesbos/eslint-config-wesbos#local--per-project-install:

image

**Comment by eglove** [comment]
I realize that. I'm just saying it's generally not a good idea to run eslint on every file in the project at once.

**Comment by ianrohde** [comment]
Open a PR then 🥃

**Pull request closed without merging**
